### ISSUE TITLE
[BUG]: Dev Container does not build from .devcontainer/devcontainer.json

### ISSUE THREAD

**Issue by sedexdev** [ShaunSHamilton/web3#109]
### Issue/Experience

Following the directions on https://web3.freecodecamp.org/web3#instructions does not result in the dev container being built using the JSON document located in `.devcontainer/devcontainer.json`.

Opening the `web3-curriculum` directory in VS Code using `code .` from bash and then running `Dev Containers: Rebuild and Reopen in Container` results in the folllowing options:

![add_config_to_workspace](https://github.com/freeCodeCamp/web3-curriculum/assets/44058834/d1a6147c-2f83-4c27-85da-19a7a9c97697)

Selecting 'Add configuration to workspace' then shows a second set of options:

![from_dockerfile](https://github.com/freeCodeCamp/web3-curriculum/assets/44058834/59f2cd6b-38fb-4ce7-8d65-acaf1db82ed6)

Selecting 'From Dockerfile' then prompts to install a number of packages which I skipped. Then the following alert pops up:

![overwrite_devcontainer_json](https://github.com/freeCodeCamp/web3-curriculum/assets/44058834/80cbc27f-1566-43a4-8c46-50e85377e4f7)

The issue here is that Dev Containers is detecting an existing configuration but is unable to read the config stored in `.devcontainer/devcontainer.json` for some reason. It is therefore prompting to overwrite it with a generic config that does not find the `Dockerfile` or set the correct context, or install the FreeCodeCamp - Courses extension in the container.

I have managed to work around this issue by doing the following:

- Moved `.devcontainer/devcontainer.json` up to the root directory and renamed to `.devcontainer.json` (as outlined in the VS Code official Dev Containers documentation - https://code.visualstudio.com/docs/devcontainers/create-dev-container)
- Deleted the now empty `.devcontainer` directory
- Edited the following fields in `.devcontainer.json`
    - `"dockerFile": "../Dockerfile"` -> `"dockerFile": "./Dockerfile"`
    - `"context": ".."` -> `"context": "."`

These changes read the `Dockerfile` from, and set the context to, the root directory, where `.devcontainer.json` now lives.

### Environment
Windows 10 - 22H2 (19045.4291)
VS Code - 1.88.1 (User Setup)
Docker Desktop - 4.29.0 (145265)
Dev Containers Extension - 0.354.0

I have also had the same issue on Ubuntu Server 22.04 LTS and this worked to fix that as well.
 
### Supporting GitHub issues

These issues may help to help explain the problem that exists within the Dev Containers extension, they helped me find a solution and eventually get access to the course material:

- https://github.com/microsoft/vscode-remote-release/issues/8830
- https://github.com/microsoft/vscode-remote-release/issues/9381

### Output of running `node tooling/camper-info.js` from the workspace root

N/A

**Comment by ShaunSHamilton** [comment]
Thank you, @sedexdev for spotting this, and suggesting a solution 🚀
