### ISSUE TITLE
[DEVX] Can't use comments at end of test

### ISSUE THREAD

**Issue by moT01** [ShaunSHamilton/web3#22]
If you have a test that looks like this:
````
```js
assert(false);
// comment
```
````

Stuff breaks, pretty sure. Not a big deal now that I know - had me pretty confused for a bit.

**Comment by ShaunSHamilton** [comment]
Sounds fun. I will fix this ASAP.

I am pretty sure the fix is to not put any comments.

**Comment by ShaunSHamilton** [comment]
@moT01 I am unable to reproduce this. Would you mind sharing more?

**Comment by moT01** [comment]
The linked PR didn't seem to fix this for me.

More info:
````
```js
console.log('test');
assert(false);
```
````
^ logs `test` when you run the tests

````
```js
console.log('test');
assert(false);
// comment
```
````
^ does not log `test` when you run the tests
