### ISSUE TITLE
[TESTS] Validate some things

### ISSUE THREAD

**Issue by moT01** [ShaunSHamilton/web3#25]
Not urgent or necessary, just making an issue with some thoughts...

We could run the markdown files through some sort of validator to make sure they all have the correct format
We could make sure all the md filenames are included in the config/projects.json
Make sure the repo has a folder name that matches the dashedName?
Make sure they're in .vscode/settings.json?

**Comment by ShaunSHamilton** [comment]
We could do this, but I was mostly of the thinking: _If you add a project, and it does not load in the UI whilst you are developing, then there is likely a parsing/config error_

I will bother @ojeytonwilliams to see if he has any experience with Markdown format validation.

---

Oliver, do we do something similar in `/freeCodeCamp`?

**Comment by ojeytonwilliams** [comment]
@ShaunSHamilton we use markdownlint, but I wouldn't recommend it.  I had to configure it quite heavily to get something reasonable. I believe remark-lint is a bit nicer, though.

Thing is, you have a parser, don't you?  What I'd recommend is checking that that is producing what you expect. What we do in the main repo is use Joi to validate the objects that the parser produces. That works quite nicely.

**Comment by ojeytonwilliams** [comment]
@ShaunSHamilton we use markdownlint, but I wouldn't recommend it.  I had to configure it quite heavily to get something reasonable. I believe remark-lint is a bit nicer, though.

Thing is, you have a parser, don't you?  What I'd recommend is checking that that is producing what you expect. What we do in the main repo is use Joi to validate the objects that the parser produces. That works quite nicely.

**Comment by ShaunSHamilton** [comment]
> What I'd recommend is checking that that is producing what you expect.

Well, we kind of do this:

https://github.com/freeCodeCamp/web3-curriculum/blob/main/.freeCodeCamp/tests/parser.test.js

**Comment by ojeytonwilliams** [comment]
That looks to be checking that the parser functions as expected, but it sounds like you might also want to validate that it's not producing gibberish.

**Comment by ShaunSHamilton** [comment]
This should be closed with: https://github.com/freeCodeCamp/freeCodeCampOS/pull/182
