### ISSUE TITLE
[UI/UX] Simple browser needs refresh before showing the client

### ISSUE THREAD

**Issue by moT01** [ShaunSHamilton/web3#28]
When I start the course - the simple browser loads itself, and stays blank until I manually refresh it.

**Comment by ShaunSHamilton** [comment]
I am not sure there is anything we can do here.

Gitpod uses websockets to control this behaviour, but I am unsure how they do it.

**Comment by ShaunSHamilton** [comment]
Possibly fixed... closing for now
