### ISSUE TITLE
[FEAT] Adjust Tooling for Multiple Projects

### ISSUE THREAD

**Issue by ShaunSHamilton** [ShaunSHamilton/web3#3]
- Dynamically hide `learn-` folders based on which project is selected.
- Push/pop content to `/` when working on project
- Discuss a decent way to persist progress locally
- - Probably will just add state to `projects.json` and move away from `.env` state

**Comment by ShaunSHamilton** [comment]
@moT01 Remind me: Did we decide:
a) Camper selects project `learn-x`, then boilerplate/contents of `learn-x/` is dumped into `/` (root of workspace)?
b) We get Campers to work in `learn-x/` directory, and dynamically hide the other non-selected directories?

**Comment by moT01** [comment]
I think we made a soft decision for b, since that's basically what you already had working. I like the UX of a better, but I feel like that may complicate things or have problems - not sure.

**Comment by ShaunSHamilton** [comment]
Well, I have gone with `a` so far. If it proves buggy or difficult to work with, then we can go with `b`.
