### ISSUE TITLE
[UI] Text gets cut off in tests/console area

### ISSUE THREAD

**Issue by moT01** [ShaunSHamilton/web3#37]
Text is cut off in test/console area on the far right:
![Screen Shot 2022-08-01 at 2 10 33 PM](https://user-images.githubusercontent.com/20648924/182227669-070a71de-a635-41e8-8652-79302939677b.png)

I thought we(you) had maybe fixed this at one point - maybe not

**Comment by ShaunSHamilton** [comment]
I am beginning to think Git is failing me/us; I am sure I fixed this at one point.
