### ISSUE TITLE
something's wrong when opening and running the course[HELP]: 

### ISSUE THREAD

**Issue by zhuimengsa** [ShaunSHamilton/web3#61]
### Question
something's wrong when opening and running the course:
freeCodeCamp Open Course:connection found. Please check your internet connection
freeCodeCamp Run Course:Unable to find a `freecodecamp.conf.json` file in workspace.
### Code and Screenshots
![image](https://user-images.githubusercontent.com/20664405/192173859-84283694-a49a-45a5-88d7-5fb212215f90.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

Others came across this error because building the Dockerfile did not correctly finish.

I suggest:
1) Delete, then reclone the repo
2) Ensure you delete the container you have already built
3) `Rebuild and Reopen Container`

Hope this helps

**Comment by guycode** [comment]
It just keeps loading the traefik dashboard for me. Cant get the actual projects to display

**Comment by ShaunSHamilton** [comment]
@guycode What does this mean? What is a "traefik dashboard"?

> It just keeps loading the traefik dashboard for me

**Comment by guycode** [comment]
I got it figured out sorry. Had another container dev proxy running in docker.

**Comment by zhuimengsa** [comment]
> 

thx a lot,I'll try it out.

**Comment by zhuimengsa** [comment]
> 

thx a lot,I'll try it out.

**Comment by zhuimengsa** [comment]
```bash
[+] Building 2.5s (25/25) FINISHED                                              
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 115B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04            2.3s
 => [ 1/19] FROM docker.io/library/ubuntu:20.04@sha256:35ab2bf57814e9ff49  0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 51.47kB                                       0.0s
 => CACHED [ 2/19] RUN apt-get update && apt-get install -y sudo           0.0s
 => CACHED [ 3/19] RUN yes | unminimize                                    0.0s
 => CACHED [ 4/19] RUN ln -snf /usr/share/zoneinfo/America/New_York /etc/  0.0s
 => CACHED [ 5/19] RUN adduser --disabled-password   --gecos '' camper     0.0s
 => CACHED [ 6/19] RUN adduser camper sudo                                 0.0s
 => CACHED [ 7/19] RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >>   /etc/sudo  0.0s
 => CACHED [ 8/19] RUN sudo apt-get install -y curl git bash-completion m  0.0s
 => CACHED [ 9/19] RUN curl -fsSL https://deb.nodesource.com/setup_18.x |  0.0s
 => CACHED [10/19] RUN sudo apt-get install -y nodejs                      0.0s
 => CACHED [11/19] RUN sudo apt-get install -y build-essential             0.0s
 => CACHED [12/19] RUN curl https://sh.rustup.rs -sSf | sh -s -- -y        0.0s
 => CACHED [13/19] RUN curl https://rustwasm.github.io/wasm-pack/installe  0.0s
 => CACHED [14/19] WORKDIR /workspace/web3-curriculum                      0.0s
 => CACHED [15/19] RUN mkdir ~/.npm-global                                 0.0s
 => CACHED [16/19] RUN npm config set prefix '~/.npm-global'               0.0s
 => CACHED [17/19] COPY . .                                                0.0s
 => CACHED [18/19] WORKDIR /workspace/web3-curriculum                      0.0s
 => CACHED [19/19] RUN cd /workspace/web3-curriculum && npm install        0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:7b9efc5af63ac3fa0a8cf170c447c36e01ff850f95b5e  0.0s
 => => naming to docker.io/library/vsc-web3-curriculum-main-c7ec923aabb30  0.0s
 => exporting cache                                                        0.0s
 => => preparing build cache for export                                    0.0s
[4026 ms] Start: Run: docker events --format {{json .}} --filter event=start
[4029 ms] Start: Starting container
```

seems successfully built the image?
But still got the same error.

**Comment by gabriel11001** [comment]
Same problem here.

**Comment by ShaunSHamilton** [comment]
@zhuimengsa It does not appear your rebuilt your container from scratch. I suggest you rebuild the container without any cache.

**Comment by zhuimengsa** [comment]
https://web3.freecodecamp.org/solana

**Comment by zhuimengsa** [comment]
Same problem for this course:https://web3.freecodecamp.org/solana.I'm sure to build the container successfully.I thought maybe this is not the key point?
I'll try rebuild the container without any cache and update if it's ok.

**Comment by mboti2000** [comment]
Hi, after running the container and starting the course, I have this error on clicking any of the courses on the main page. Restarting the course doesn't solve the problem.

![error](https://user-images.githubusercontent.com/71784398/193116094-361d4729-1e12-4ea0-87b1-b33c0ba21b1d.png)

**Comment by ShaunSHamilton** [comment]
@mboti2000 Would you be able to open a new issue, and fill in the details there?

**Comment by zhuimengsa** [comment]
> Same problem for this course:https://web3.freecodecamp.org/solana.I'm sure to build the container successfully.I thought maybe this is not the key point? I'll try rebuild the container without any cache and update if it's ok.

still not working
