### ISSUE TITLE
[HELP]: Error after starting the course

### ISSUE THREAD

**Issue by mboti2000** [ShaunSHamilton/web3#64]
Hi, I started the container, and the course too, but when I click on any of the courses on the main page, I get the following error on the screen. Restarting the course doesn't solve the problem.

![error](https://user-images.githubusercontent.com/71784398/193119809-fe51ab75-e9a8-439a-802a-c24b7c3c556b.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

Would you please run `node tooling/camper-info.js` in your terminal and share the output? For future issues, please use one of the given issue templates.

**Comment by mboti2000** [comment]
This is the output after running the command,

![output](https://user-images.githubusercontent.com/71784398/193121046-fd7dff8b-95c1-42c1-8d99-46a5b10fb334.PNG)

**Comment by ShaunSHamilton** [comment]
I am unable to reproduce any issue here.

I suggest clearing all Docker cache, and rebuilding the container, and trying again.

**Comment by mboti2000** [comment]
Thank you, it seems it solved the problem. I close the issue.
