### ISSUE TITLE
[BUG]: Issue with server

### ISSUE THREAD

**Issue by hardikrangucha** [ShaunSHamilton/web3#68]
### Output of running `node tooling/camper-info.js` from the workspace root

I did everything said in instructions steps after I run freeCodeCamp run course when  I select any course in freeCodeCamp it shows me "Error 4XX - 5XX
Client has disconnected from local server

To Keep Learning:
First, try refresh this page
Otherwise:
Open the command palette
Select the freeCodeCamp: Shutdown Course command
Open the command palette
Select the freeCodeCamp: Run Course command"

I tried to shutdown and run it again but still the same

**Comment by ShaunSHamilton** [comment]
Hello there,

Please follow the issue template, when opening an issue.
