### ISSUE TITLE
[BUG]: Error 4XX - 5XX Client has disconnected from local server

### ISSUE THREAD

**Issue by javiervelaz** [ShaunSHamilton/web3#69]
### Issue/Experience
when a course was selected

Error 4XX - 5XX
Client has disconnected from local server

### Output of running `node tooling/camper-info.js` from the workspace root
root@ad75d85957e7:/workspace/web3-curriculum# node tooling/camper-info.js
🔵 INFO:   Project:  build-a-fundraising-smart-contract
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.1
🔵 INFO:   freeCodeCamp - Courses:  freeCodeCamp.freecodecamp-courses@1.6.0
🔵 INFO:   Commit:  abb0cea chore(0.1.1): update freecodecamp-os to 1.6.5 (#63)

🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 5.10.16.3-microsoft-standard-WSL2
    Type: Linux

**Comment by ShaunSHamilton** [comment]
Hello there,

I am unable to replicate any issue with the curriculum.

I suggest clearing your Docker cache, and rebuilding the container from scratch.
