### ISSUE TITLE
[BUG]: Error 4XX - 5XX Client has disconnected from local server

### ISSUE THREAD

**Issue by geordanex** [ShaunSHamilton/web3#70]
### Issue/Experience
I have an error when entering any course. I followed all the steps and even run again from scratch and nothing.
I also checked the docker cache and cleaned.

### Output of running `node tooling/camper-info.js` from the workspace root
root@4bb3d0f8b194:/workspace/web3-curriculum# cd . && NODE_ENV=production node ./.freeCodeCamp/tooling/server.js
🔵 INFO:  2022-10-27 00:03:22 Listening on port 8080
🔵 INFO:  2022-10-27 00:03:24 Watching for file changes on /workspace/web3-curriculum
🔵 INFO:  2022-10-27 00:03:32 Watching for file changes on /workspace/web3-curriculum
file:///workspace/web3-curriculum/.freeCodeCamp/tooling/parser.js:200
  const mat = lesson.match(
                     ^

TypeError: Cannot read properties of undefined (reading 'match')
    at parseMarker (file:///workspace/web3-curriculum/.freeCodeCamp/tooling/parser.js:200:22)
    at getLessonDescription (file:///workspace/web3-curriculum/.freeCodeCamp/tooling/parser.js:62:23)
    at runLesson (file:///workspace/web3-curriculum/.freeCodeCamp/tooling/lesson.js:35:23)
    at async FSWatcher.<anonymous> (file:///workspace/web3-curriculum/.freeCodeCamp/tooling/hot-reload.js:47:7)

Node.js v18.12.0

**Comment by geordanex** [comment]
Also the camper info
🔵 INFO:   Project:  build-a-video-game-marketplace-blockchain
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.1
🔵 INFO:   freeCodeCamp - Courses:  freeCodeCamp.freecodecamp-courses@1.6.0
🔵 INFO:   Commit:  abb0cea chore(0.1.1): update freecodecamp-os to 1.6.5 (#63)

🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 5.10.16.3-microsoft-standard-WSL2
    Type: Linux

**Comment by ShaunSHamilton** [comment]
Hello there,

I am unable to reproduce any issue with this curriculum.

Would you mind also running: `node tooling/camper-info.js --history --directory` and sharing the output.

**Comment by geordanex** [comment]
Here is the output

root@cfe4c9fdfe28:/workspace/web3-curriculum# node tooling/camper-info.js --history --directory
🔵 INFO:   Project:  build-a-video-game-marketplace-blockchain
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.1
🔵 INFO:   freeCodeCamp - Courses:  freeCodeCamp.freecodecamp-courses@1.6.0
🔵 INFO:   Commit:  abb0cea chore(0.1.1): update freecodecamp-os to 1.6.5 (#63)

🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 5.10.16.3-microsoft-standard-WSL2
    Type: Linux
    
🔵 INFO:   Command History:
 
🔵 INFO:   ||-- build-a-video-game-marketplace-blockchain
🔵 INFO:   |  |-- build-a-video-game-marketplace-blockchain/.tests
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test1
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test10
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test2
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test3
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test4
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test5
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test6
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test7
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test8
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test9
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |  |-- blockchain-helpers.js
🔵 INFO:   |  |-- blockchain.json
🔵 INFO:   |  |-- buy-item.js
🔵 INFO:   |  |-- example-blockchain.json
🔵 INFO:   |  |-- example-transactions.json
🔵 INFO:   |  |-- example-wallets.json
🔵 INFO:   |  |-- generate-wallet.js
🔵 INFO:   |  |-- get-address-info.js
🔵 INFO:   |  |-- gift-items.js
🔵 INFO:   |  |-- init-blockchain.js
🔵 INFO:   |  |-- items.json
🔵 INFO:   |  |-- mine-block.js
🔵 INFO:   |  |-- sell-item.js
🔵 INFO:   |  |-- transactions.json
🔵 INFO:   |  |-- wallets.json

**Comment by isaacudofia** [comment]
t's not a "user" error, it's a [client error](https://www.rfc-editor.org/rfc/rfc9110.html#name-client-error-4xx); but yeah, that's a lousy label. The labels reflect the [client-server architectural constraint](https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm#sec_5_1_2), but it might be better to use labels that point more directly at the contents of the request, rather than the client (or the user).

In practice, it's a client error for the same reason that [404](https://www.rfc-editor.org/rfc/rfc9110.html#name-404-not-found) is a client error; it is specifically calling attention to the target resource of the HTTP request.

In the context of the web, it does make some (imperfect) sense - the client followed a broken link (which could be a consequence of the server's current representations, but might also come from following links in stale representations, following stale bookmarks, a spelling error in a representation provided by a different server, etc).

**Comment by sathwic97** [comment]
I too am experiencing the same issue. Please help us out.




root@74fae7338539:/workspace/web3-curriculum# cd . && NODE_ENV=production node ./.freeCodeCamp/tooling/server.js
🔵 INFO:  2022-11-03 01:54:42 Listening on port 8080
🔵 INFO:  2022-11-03 01:54:46 Watching for file changes on /workspace/web3-curriculum
file:///workspace/web3-curriculum/.freeCodeCamp/tooling/parser.js:200
  const mat = lesson.match(
                     ^

TypeError: Cannot read properties of undefined (reading 'match')
    at parseMarker (file:///workspace/web3-curriculum/.freeCodeCamp/tooling/parser.js:200:22)
    at getLessonDescription (file:///workspace/web3-curriculum/.freeCodeCamp/tooling/parser.js:62:23)
    at runLesson (file:///workspace/web3-curriculum/.freeCodeCamp/tooling/lesson.js:35:23)

Node.js v18.12.0
root@74fae7338539:/workspace/web3-curriculum# node tooling/camper-info.js --history --directory
🔵 INFO:   Project:  build-a-video-game-marketplace-blockchain
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.1
🔵 INFO:   freeCodeCamp - Courses:  freeCodeCamp.freecodecamp-courses@1.6.0
🔵 INFO:   Commit:  abb0cea chore(0.1.1): update freecodecamp-os to 1.6.5 (#63)

🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 5.10.16.3-microsoft-standard-WSL2
    Type: Linux
    
🔵 INFO:   Command History:
 
🔵 INFO:   ||-- build-a-video-game-marketplace-blockchain
🔵 INFO:   |  |-- build-a-video-game-marketplace-blockchain/.tests
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test1
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test10
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test2
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test3
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test4
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test5
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test6
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test7
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test8
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |    |-- build-a-video-game-marketplace-blockchain/.tests/test9
🔵 INFO:   |      |-- .gitkeep
🔵 INFO:   |  |-- blockchain-helpers.js
🔵 INFO:   |  |-- blockchain.json
🔵 INFO:   |  |-- buy-item.js
🔵 INFO:   |  |-- example-blockchain.json
🔵 INFO:   |  |-- example-transactions.json
🔵 INFO:   |  |-- example-wallets.json
🔵 INFO:   |  |-- generate-wallet.js
🔵 INFO:   |  |-- get-address-info.js
🔵 INFO:   |  |-- gift-items.js
🔵 INFO:   |  |-- init-blockchain.js
🔵 INFO:   |  |-- items.json
🔵 INFO:   |  |-- mine-block.js
🔵 INFO:   |  |-- sell-item.js
🔵 INFO:   |  |-- transactions.json
🔵 INFO:   |  |-- wallets.json
root@74fae7338539:/workspace/web3-curriculum#

**Comment by ShaunSHamilton** [comment]
@sathwic97 

Thank you for the details. Unfortunately, I am unable to reproduce any issue.

**Comment by moT01** [comment]
You should be able to run `freeCodeCamp: Run Course` to load it back up and it should work.

**Comment by nguyentri-art** [comment]
Hello ! Please help . i'm just do any step and this put out a blank page with freeCodeCamp logo , and then it's have a error Error 4XX - 5XX Client has disconnected from local server like tittle , i'm try run `freeCodeCamp: shutdown course ` and `freeCodeCamp: Run Course` like tutorial but not thing happend . That make me more than a day loop with . Please help
