### ISSUE TITLE
[HELP]: Unable to find a freecodecamp.conf.json file in workspace.

### ISSUE THREAD

**Issue by ghost** [ShaunSHamilton/web3#72]
### Project
web3-curriculum

### Question
Unable to find a `freecodecamp.conf.json` file in workspace.

### Code and Screenshots
When I run freeCodeCamp: Run Course. it pops up the error message "Unable to find a `freecodecamp.conf.json` file in workspace."
![image](https://user-images.githubusercontent.com/7302449/199520775-f5fccf66-81b5-45c0-987e-34579ec0d39f.png)

**Comment by ShaunSHamilton** [comment]
@JayceeQ Thank you for opening this.

Would you mind doing the following:
1) Open the dev console
2) Run the `freeCodeCamp: Run Course` command again
3) Share any errors you get in the console

**Comment by ghost** [comment]
@ShaunSHamilton  sure, thanks for your support.  I run the first step successfully with "Dev Containers: Rebuild Container and Reopen in Container" 
![Rebuild Container and Reopen in Container](https://user-images.githubusercontent.com/7302449/200018452-73a4922b-a146-43dd-8d51-737f2173177e.PNG)

and then I try to run "freeCodeCamp: Run Course ", but there is no log in debug console. 

![RunCourse](https://user-images.githubusercontent.com/7302449/200018569-d04d641b-a882-4298-8791-0c7a6efd192d.PNG)

**Comment by ghost** [comment]
attach more info FYR
![image](https://user-images.githubusercontent.com/7302449/200019746-0235f637-63e3-49e8-b7b2-6a84abcea2f1.png)

**Comment by ShaunSHamilton** [comment]
@JayceeQ VSCode is an electron app - you can open the dev console, with `CTRL + SHIFT + I`. OR, go to the top task bar, `Help`, and `Toggle Developer Tools`.

Hope this clarifies

**Comment by ghost** [comment]
Hi @ShaunSHamilton , thanks for sharing this, it helps a lot as I'm not familiar with VSCode, now I can run the "run course" cmd successfully which is exciting for me to begin my web3 journey.

The root cause for this error is that the program needs to download the configuration file from GitHub raw. Due to some reason, my computer can't reach the GitHub raw DNS, but luckily I find out how to solve the issue.  

However, may I ask one more question?  Why we don't use the "freecodecamp.conf.json" file locally which I just cloned from the remote repo and use HTTPS  to query the remote file instead? 
![image](https://user-images.githubusercontent.com/7302449/200128819-02be1cc7-f5f5-4f1b-b1b4-b4363c427ebe.png)

Thanks & regard

**Comment by ghost** [comment]
Hi @ShaunSHamilton, thanks for sharing this, it helps a lot as I'm not familiar with VSCode, now I can run the "run course" cmd successfully which is exciting for me to begin my web3 journey.

The root cause for this error is that the program needs to download the configuration file from GitHub raw. Due to some reason, my computer can't reach the GitHub raw DNS, but luckily I find out how to solve the issue.  

However, may I ask one more question?  Why we don't use the "freecodecamp.conf.json" file locally which I just cloned from the remote repo and use HTTPS  to query the remote file instead? 
![image](https://user-images.githubusercontent.com/7302449/200128819-02be1cc7-f5f5-4f1b-b1b4-b4363c427ebe.png)

Thanks & regard

**Comment by ShaunSHamilton** [comment]
Thank you. That does make sense now. 
I think I understand what is going on. 

The online freecodecamp.conf.json file is fetched in order to determine if you have the latest changes - in cases where we fix bugs, or add more lessons.

So, the error message is a bit misleading.
