### ISSUE TITLE
[learn-proof-of-work-consensus-by-building-a-block-mining-algorithm]: review feedback

### ISSUE THREAD

**Issue by ShaunSHamilton** [ShaunSHamilton/web3#74]
**ISSUES**

- [ ] 4: Extra sentence in description?
- [ ] 7: `TypeError: __helpers.babeliser is not a function`
  - https://github.com/freeCodeCamp/web3-curriculum/pull/71#discussion_r1019377937
- [ ] 8: "... into a 256<b>-</b>bit hash ..."
- [ ] 12: Lesson glitched, and tests failed - probably nothing to do here - manually running tests passed.
  - I mention in the case you have weird timeouts that might be causing this
- [ ] 64: "... and see if **it** matches ..."
- [ ] 64: I used `previousHash`, but test expects `previousBlock.hash`
- [ ] 74: Why the first property?
- [ ] 105: ugly regex test. I did `if (address === fromAddress)`

**SUGGESTIONS**

1) A few errors in the console due to `Cannot read properties of undefined` - **OPTIONAL CHAINING**

---

Flow is excellent! You are a master teacher, Tom 😮 
Thank you for using _"object literal"_ 😁 

"This is fun"

**Comment by moT01** [comment]
Thanks for the feedback and compliment @ShaunSHamilton 👍 I need to tell them they are having fun - or else they might not know.

I will take a look at these when I get a chance.

**Comment by moT01** [comment]
These were addressed in https://github.com/freeCodeCamp/web3-curriculum/pull/83
