### ISSUE TITLE
[HELP]:  Unable to build the Docker file

### ISSUE THREAD

**Issue by Poudel0** [ShaunSHamilton/web3#86]
### Code and Screenshots 
New to Docker and dont know how to fix this
![image](https://user-images.githubusercontent.com/47084739/215467147-55ae60ac-3de4-42d2-abf9-46bfbf3369b8.png)

**Comment by ShaunSHamilton** [comment]
Hello there,

I am unable to reproduce any issue with building the container image.

I notice you are starting this with the tooling cached. Have you tried to rebuild (without cache)? It might have failed as a fluke.

**Comment by Poudel0** [comment]
I installed npm in the directory with just` npm install` and rebuild (without cache) and it worked for me.

**Comment by Poudel0** [comment]
But for some reason no links open? I click and nothing happens?

![image](https://user-images.githubusercontent.com/47084739/215539292-208da35a-6099-4d46-b8c2-d7dcf6c87cea.png)

**Comment by ShaunSHamilton** [comment]
> I click and nothing happens?

I am unable to reproduce any issues. So, I cannot say what the problem is.

If you can provide any more details, then we can try debugging further.

**Comment by Poudel0** [comment]
![image](https://user-images.githubusercontent.com/47084739/215650812-6b5e1076-822d-4e8b-9080-56341df0f574.png)

**Comment by Poudel0** [comment]
https://www.veed.io/view/ffae7484-7410-43b3-9e8c-b0e1ee4f1753?sharingWidget=true&panel=share

**Comment by ShaunSHamilton** [comment]
@Poudel0 Thank you for that.

The odd thing I notice is your Git tree is not clean - you have many uncommitted changes, which should not be the case.

Could you:
1) Show what those changes are (224 changes)
2) Try reverting the changes (click the undo changes button)

**Comment by Poudel0** [comment]
I really dont know whats supposed to be here.
After I rebuild, git changes show up. Its normal before that. but the files itself seem unchanged?
![image](https://user-images.githubusercontent.com/47084739/216367642-ec5f9fcf-4c54-44c3-a819-8f2b5fe6fbae.png)

**Comment by ShaunSHamilton** [comment]
There should not be any git changes. Try reverting the changes, even if some/all of them appear unchanged.

**Comment by Poudel0** [comment]
thanks it worked
