### ISSUE TITLE
Unable to start the lesson - 'Learn Digital Ledgers by Building a Blockchain'

### ISSUE THREAD

**Issue by SandeepGumaste** [ShaunSHamilton/web3#87]
**Description**
Unable to start the lesson - 'Learn Digital Ledgers by Building a Blockchain'

**To Reproduce**
run course and click on first lesson - 'Learn Digital Ledgers by Building a Blockchain'

**Screenshots**
![image](https://user-images.githubusercontent.com/73634237/216787327-10d39ff5-9f79-45f7-8540-1f6c35b679a3.png)

**Desktop:**
 - OS: Windows11
 - Browser: Brave

**Comment by Parczynski** [comment]
Have the same error. However if I connect to docker container, I can see that the file learn-digital-ledgers-by-building-a-blockchain.md is in its place.

**Comment by Parczynski** [comment]
It looks like .freeCodeCamp/tooling/parser.js is searching for \n as a line break, but all your .md files uses \r\n for line breaks.

**Comment by ShaunSHamilton** [comment]
Hello there,

Notice you have 224 Git changes. I suggest reverting those changes, and trying again.
